version: "3.3"
services:
  users_db:
    image: postgres:11.5-alpine
    container_name: users_db
    environment:
      POSTGRES_PASSWORD: ${USERS_POSTGRES_PASSWORD}
      POSTGRES_USER: ${USERS_POSTGRES_USER}
      POSTGRES_DB: ${USERS_POSTGRES_DB}
    volumes:
      - ./users/docker/db/init-db.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    networks:
      - users
    ports:
      - 15432:5432
  users_app:
    build:
      context: .
      dockerfile: docker/users_app/Dockerfile
    container_name: users_app
    volumes:
      - "../:/go/src/users"
    ports:
      - "8080:3000"
    tty: true
    depends_on:
      - users_db
    networks:
      - users
networks:
  users:
volumes:
  db: